@echo off
SET SSL_CHECKER_PATH_FOLDER=%~dp0
SET SSL_CHECKER_FILE_NAME=%SSL_CHECKER_PATH_FOLDER%ssl_checker_script.py
SET SSL_CHECKER_LOG_FILE=%SSL_CHECKER_PATH_FOLDER%log\ssl_checker.log

python %SSL_CHECKER_FILE_NAME% > %SSL_CHECKER_LOG_FILE% 2>&1